version: '3.8'

services:
  drupal:
    image: drupal:10.0-fpm
    volumes:
      - www-data:/var/www/html
    restart: unless-stopped
    depends_on:
      - mariadb

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - www-data:/var/www/html
    depends_on:
      - mariadb
    
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_USER: melvincv
      MARIADB_PASSWORD: )#4s<NgiHZoMCA"){kL)
      MARIADB_ROOT_PASSWORD: <~#9[(n%K./'(_3$|[DR
      MARIADB_DATABASE: mcvdrdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

volumes:
  www-data:
  db-data: