version: '3.8'

services:
  drupal:
    image: drupal:10.0
    ports:
      - 8001:80
    volumes:
      - dr-modules:/var/www/html/modules
      - dr-profiles:/var/www/html/profiles
      - dr-themes:/var/www/html/themes
      - dr-sites:/var/www/html/sites
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_USER: melvincv
      MARIADB_PASSWORD: 
      MARIADB_ROOT_PASSWORD: 
      MARIADB_DATABASE: mcvdrdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

volumes:
  dr-modules:
  dr-profiles:
  dr-themes:
  dr-sites:
  db-data: